spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: account_admin
    password: Qwer!234Asdf
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true